#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*                linuxserver/deluge                  *
*                                                    *
*     https://hub.docker.com/r/linuxserver/deluge    *
*                                                    *
*    https://github.com/linuxserver/docker-deluge    *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
